/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package globalcustody1;

/**
 *
 * @author FOYSAL
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        custbtn2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bnkbtnv = new javax.swing.JButton();
        bankbtn = new javax.swing.JLabel();
        bndbtn = new javax.swing.JButton();
        bondbtn = new javax.swing.JLabel();
        assetbton = new javax.swing.JButton();
        asstbtn = new javax.swing.JLabel();
        refbtn = new javax.swing.JButton();
        calndrbtn = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        othbtn = new javax.swing.JButton();
        otherlvl = new javax.swing.JLabel();
        codibtn = new javax.swing.JButton();
        odilbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        custbtn3 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Form");
        setBackground(new java.awt.Color(204, 204, 204));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));

        custbtn2.setBackground(new java.awt.Color(51, 0, 51));
        custbtn2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        custbtn2.setForeground(new java.awt.Color(51, 0, 51));
        custbtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project Icon/Customer Icon.png"))); // NOI18N
        custbtn2.setText("Customer");
        custbtn2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        custbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custbtn2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Customer");

        bnkbtnv.setBackground(new java.awt.Color(51, 0, 51));
        bnkbtnv.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        bnkbtnv.setForeground(new java.awt.Color(51, 0, 51));
        bnkbtnv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project Icon/Bank Icon.png"))); // NOI18N
        bnkbtnv.setText("Customer");
        bnkbtnv.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bnkbtnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnkbtnvActionPerformed(evt);
            }
        });

        bankbtn.setBackground(new java.awt.Color(255, 255, 255));
        bankbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bankbtn.setForeground(new java.awt.Color(255, 255, 255));
        bankbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bankbtn.setText("Bank");

        bndbtn.setBackground(new java.awt.Color(51, 0, 51));
        bndbtn.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        bndbtn.setForeground(new java.awt.Color(51, 0, 51));
        bndbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project Icon/Bond Icon.png"))); // NOI18N
        bndbtn.setText("Customer");
        bndbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bndbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bndbtnActionPerformed(evt);
            }
        });

        bondbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bondbtn.setForeground(new java.awt.Color(255, 255, 255));
        bondbtn.setText("Bonds");

        assetbton.setBackground(new java.awt.Color(51, 0, 51));
        assetbton.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        assetbton.setForeground(new java.awt.Color(51, 0, 51));
        assetbton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project Icon/Asset Icon.png"))); // NOI18N
        assetbton.setText("Customer");
        assetbton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        assetbton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assetbtonActionPerformed(evt);
            }
        });

        asstbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        asstbtn.setForeground(new java.awt.Color(255, 255, 255));
        asstbtn.setText("Assets");

        refbtn.setBackground(new java.awt.Color(51, 0, 51));
        refbtn.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        refbtn.setForeground(new java.awt.Color(51, 0, 51));
        refbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project Icon/Settlements Icon.png"))); // NOI18N
        refbtn.setText("Customer");
        refbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        refbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refbtnActionPerformed(evt);
            }
        });

        calndrbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        calndrbtn.setForeground(new java.awt.Color(255, 255, 255));
        calndrbtn.setText("Sattlements");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Home");

        othbtn.setBackground(new java.awt.Color(51, 0, 51));
        othbtn.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        othbtn.setForeground(new java.awt.Color(51, 0, 51));
        othbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project Icon/Exit Icon.png"))); // NOI18N
        othbtn.setText("Customer");
        othbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        othbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                othbtnActionPerformed(evt);
            }
        });

        otherlvl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        otherlvl.setForeground(new java.awt.Color(255, 255, 255));
        otherlvl.setText("Exit");

        codibtn.setBackground(new java.awt.Color(51, 0, 51));
        codibtn.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        codibtn.setForeground(new java.awt.Color(51, 0, 51));
        codibtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project Icon/Custodian Icon.png"))); // NOI18N
        codibtn.setText("Customer");
        codibtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        codibtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codibtnActionPerformed(evt);
            }
        });

        odilbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        odilbl.setForeground(new java.awt.Color(255, 255, 255));
        odilbl.setText("Custodian");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project Icon/home.png"))); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(codibtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(odilbl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bnkbtnv, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bankbtn))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(custbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(refbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(calndrbtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(assetbton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(asstbtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bndbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bondbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(othbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(otherlvl)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(custbtn2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codibtn)
                    .addComponent(odilbl))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnkbtnv)
                    .addComponent(bankbtn))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bndbtn)
                    .addComponent(bondbtn))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assetbton)
                    .addComponent(asstbtn))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refbtn)
                    .addComponent(calndrbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(othbtn)
                    .addComponent(otherlvl))
                .addGap(75, 75, 75))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 480));

        jPanel2.setLayout(null);
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jPanel6.setLayout(null);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel6.add(jLabel4);
        jLabel4.setBounds(30, 10, 120, 110);

        jPanel7.setLayout(null);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel7.add(jLabel5);
        jLabel5.setBounds(30, 10, 120, 110);

        custbtn3.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        custbtn3.setForeground(new java.awt.Color(51, 102, 255));
        custbtn3.setText("Customer");
        custbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custbtn3ActionPerformed(evt);
            }
        });
        jPanel7.add(custbtn3);
        custbtn3.setBounds(50, 130, 83, 25);

        jPanel6.add(jPanel7);
        jPanel7.setBounds(0, 0, 0, 0);

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 190, 160));

        jPanel8.setBackground(new java.awt.Color(102, 0, 153));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Administrations");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Global Custody");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addContainerGap(355, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 530, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void custbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custbtn2ActionPerformed
       Customers cust=new Customers();
       cust.setVisible(true);
    }//GEN-LAST:event_custbtn2ActionPerformed

    private void custbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custbtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custbtn3ActionPerformed

    private void bnkbtnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnkbtnvActionPerformed
     Bank bank=new Bank();
     bank.setVisible(true);
    }//GEN-LAST:event_bnkbtnvActionPerformed

    private void bndbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bndbtnActionPerformed
      Bonds bnd=new Bonds();
      bnd.setVisible(true);
    }//GEN-LAST:event_bndbtnActionPerformed

    private void assetbtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assetbtonActionPerformed
       Assets ast=new Assets();
       ast.setVisible(true);
    }//GEN-LAST:event_assetbtonActionPerformed

    private void refbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refbtnActionPerformed
        Sattlements stl=new Sattlements();
        stl.setVisible(true);
    }//GEN-LAST:event_refbtnActionPerformed

    private void othbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_othbtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_othbtnActionPerformed

    private void codibtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codibtnActionPerformed
        Custodian custd=new Custodian();
        custd.setVisible(true);
    }//GEN-LAST:event_codibtnActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainPage().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assetbton;
    private javax.swing.JLabel asstbtn;
    private javax.swing.JLabel bankbtn;
    private javax.swing.JButton bndbtn;
    private javax.swing.JButton bnkbtnv;
    private javax.swing.JLabel bondbtn;
    private javax.swing.JLabel calndrbtn;
    private javax.swing.JButton codibtn;
    private javax.swing.JButton custbtn2;
    private javax.swing.JButton custbtn3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel odilbl;
    private javax.swing.JButton othbtn;
    private javax.swing.JLabel otherlvl;
    private javax.swing.JButton refbtn;
    // End of variables declaration//GEN-END:variables
}
